/*
 * The Gubbins Microcontroller Operating System
 *
 * Copyright 2026 Zynaptic Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*
 * This header defines the common API for processing service discovery
 * DNS requests. It is not an independent service, but is designed for
 * direct integration into other service client modules.
 */

#ifndef GMOS_OPENTHREAD_SDDNS_H
#define GMOS_OPENTHREAD_SDDNS_H

#include <stdint.h>
#include <stdbool.h>
#include "gmos-openthread.h"

/**
 * Defines the GubbinsMOS OpenThread SD-DNS client structure that is used
 * for encapsulating all the SD-DNS client data.
 */
typedef struct gmosOpenThreadSdDnsClient_t {

    // This is a pointer to the string which identifies the required
    // service.
    const char* serviceName;

    // This is the timeout that is used to force an SD-DNS refresh cycle
    // when the SD-DNS entry is stale.
    uint32_t sdDnsTimeout;

    // Timestamp the last completed SD-DNS transaction.
    uint32_t sdDnsTimestamp;

    // This is the remote CoAP UDP port number to be used for accessing
    // the discovered service.
    uint16_t servicePort;

    // Specify the current SD-DNS client state.
    uint8_t sdDnsClientState;

    // This specifies the current backoff delay for SD-DNS requests.
    uint8_t sdDnsBackoffDelay;

    // This is the IPv6 address to be used for accessing the discovered
    // service.
    uint8_t serviceAddr [16];

    // This is the SD-DNS service label which is used to identify the
    // correct SD-DNS service during refresh cycles (the first 63 octet
    // label in the fully qualified service name).
    char sdDnsLabel [64];

} gmosOpenThreadSdDnsClient_t;

/**
 * Initialises the SD-DNS client on startup.
 * @param sdDnsClient This is the SD-DNS client instance that is to be
 *     initialised on startup.
 * @param serviceName This is a pointer to a string which contains the
 *     service name used in SD-DNS discovery. It must remain valid for
 *     the lifetime of the SD-DNS client service.
 */
void gmosOpenThreadSdDnsClientInit (
    gmosOpenThreadSdDnsClient_t* sdDnsClient, const char* serviceName);

/**
 * Resets the SD-DNS client state. This clears the SD-DNS service label
 * so that a different matching service may be selected on the next
 * discovery cycle.
 * @param sdDnsClient This is the SD-DNS client instance that is to be
 *     reset.
 */
void gmosOpenThreadSdDnsClientReset (
    gmosOpenThreadSdDnsClient_t* sdDnsClient);

/**
 * Indicates whether the current SD-DNS client data is valid. If this
 * function indicates that the data is valid, the service address and
 * service port fields of the SD-DNS client data structure will contain
 * valid data.
 * @param sdDnsClient This is the SD-DNS client instance that is to be
 *     checked for valid data.
 * @return Returns a boolean value which will be set to 'true' if the
 *     service address and service port fields contain valid data.
 */
bool gmosOpenThreadSdDnsClientDataValid (
    gmosOpenThreadSdDnsClient_t* sdDnsClient);

/**
 * Periodically polls the SD-DNS client instance while an SD-DNS lookup
 * is in progress.
 * @param openThreadStack This is the OpenThread stack instance that is
 *     to be used for accessing the OpenThread network.
 * @param sdDnsClient This is the SD-DNS client instance that is to be
 *     polled in order to process the internal state machine.
 * @return Returns the task status generated by the SD-DNS internal
 *     state machine. As a special case, a 'run immediate' status
 *     indicates that the SD-DNS lookup is complete and the client data
 *     is valid.
 */
gmosTaskStatus_t gmosOpenThreadSdDnsClientPoll (
    gmosOpenThreadStack_t* openThreadStack,
    gmosOpenThreadSdDnsClient_t* sdDnsClient);

#endif // GMOS_OPENTHREAD_SDDNS_H
