/*
 * The Gubbins Microcontroller Operating System
 *
 * Copyright 2026 Zynaptic Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*
 * This header defines the common API for requesting CoRE link
 * information from the well-known CoRE resource path on a given CoAP
 * endpoint according to RFC 6690. It is not an independent service, but
 * is designed for direct integration into other service client modules.
 */

#ifndef GMOS_OPENTHREAD_WKCREQ_H
#define GMOS_OPENTHREAD_WKCREQ_H

#include <stdint.h>
#include <stdbool.h>
#include "gmos-openthread.h"

/**
 * Defines the GubbinsMOS OpenThread well-known CoRE request client
 * structure that is used for encapsulating all the request client data.
 */
typedef struct gmosOpenThreadWkcReqClient_t {

    // This is a pointer to the string which specifies the URL query
    // option to be used in requests.
    const char* queryString;

    // This is the timeout that is used to force a well-known CoRE
    // refresh cycle when the well-known CoRE data is stale.
    uint32_t wkcReqTimeout;

    // Timestamp the last completed well-known CoRE transaction.
    uint32_t wkcReqTimestamp;

    // Specify the current well-known CoRE request client state.
    uint8_t wkcReqClientState;

    // This specifies the current backoff delay for well-known CoRE
    // requests.
    uint8_t wkcReqBackoffDelay;

    // This is the URI path component of the discovered resource.
    char uriPath [32];

} gmosOpenThreadWkcReqClient_t;

/**
 * Initialises the well-known CoRE request client on startup.
 * @param wkcReqClient This is the well-known CoRE request client
 *     instance that is to be initialised on startup.
 * @param queryString This is a pointer to a string which contains the
 *     query string used in well-known CoRE requests. It must remain
 *     valid for the lifetime of the client service.
 */
void gmosOpenThreadWkcReqClientInit (
    gmosOpenThreadWkcReqClient_t* wkcReqClient, const char* queryString);

/**
 * Resets the well-known CoRE request client state. This clears the
 * discovered URI path that a different matching resource may be
 * selected on the next discovery cycle.
 * @param wkcReqClient This is the well known CoRE request client
 *     instance that is to be reset.
 */
void gmosOpenThreadWkcReqClientReset (
    gmosOpenThreadWkcReqClient_t* wkcReqClient);

/**
 * Indicates whether the current well-known CoRE request client data is
 * valid. If this function indicates that the data is valid, the
 * discovered URI path field of the well-known CoRE request client data
 * structure will contain valid data.
 * @param wkcReqClient This is the well-known CoRE client request
 *     instance that is to be checked for valid data.
 * @return Returns a boolean value which will be set to 'true' if the
 *     discovered URI path field contains valid data.
 */
bool gmosOpenThreadWkcReqClientDataValid (
    gmosOpenThreadWkcReqClient_t* wkcReqClient);

/**
 * Periodically polls the well-known CoRE request client instance while
 * a well-known CoRE request is in progress.
 * @param openThreadStack This is the OpenThread stack instance that is
 *     to be used for accessing the OpenThread network.
 * @param wkcReqClient This is the well-known CoRE client request
 *     instance that is to be polled in order to process the internal
 *     state machine.
 * @param sdDnsClient This is the SD-DNS client instance that contains
 *     the valid IP address and port for accessing the remote server.
 * @return Returns the task status generated by the well-known CoRE
 *     request client internal state machine. As a special case, a
 *     'run immediate' status indicates that the well-known CoRE request
 *     is complete and the client data is valid.
 */
gmosTaskStatus_t gmosOpenThreadWkcReqClientPoll (
    gmosOpenThreadStack_t* openThreadStack,
    gmosOpenThreadWkcReqClient_t* wkcReqClient,
    gmosOpenThreadSdDnsClient_t* sdDnsClient);

#endif // GMOS_OPENTHREAD_WKCREQ_H
