/*
 * The Gubbins Microcontroller Operating System
 *
 * Copyright 2022 Zynaptic Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*
 * This header is required by the Raspberry Pi Pico SDK. When using the
 * default SDK build process it is normally generated by CMAKE, but a
 * hardcoded version is used here which sets the common options used
 * by the GubbinsMOS port.
 */

#ifndef PICO_CONFIG_AUTOGEN_H
#define PICO_CONFIG_AUTOGEN_H

// The Pico SDK is running on the target device.
#define PICO_ON_DEVICE 1

// Do not trap on integer division by zero. The 'C' standard leaves this
// behaviour as undefined.
#define PICO_DIVIDER_CALL_IDIV0 0
#define PICO_DIVIDER_CALL_LDIV0 0

// Disable support for Pico SDK timed alarms. The corresponding hardware
// resources are used by the GubbinsMOS hardware timer driver.
#define PICO_TIME_DEFAULT_ALARM_POOL_DISABLED 1

// Use the compact printf library from the Pico SDK.
#define LIB_PICO_PRINTF_PICO 1

// Include the standard configuration options for the Raspberry Pi
// Pico system on module.
#include "boards/pico.h"

#endif // PICO_CONFIG_AUTOGEN_H
